name: CI-Go

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-go:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: Setup go
            uses: actions/setup-go@v3
            with:
                go-version: '1.19'
          - run: |
              go version
              run hello.go
          - name: Build the Go Program
            run: |
             go build hello.go
          - name: Run the Compiled Program
            run: |
              ./hello
